spring:
  profiles:
    active: dev
server:
  port: 8001
---
spring:
  profiles: dev
server:
  port: 8001
mybatis:
  type-aliases-package: com.zhirong.testdemo.pojo
#  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
spring:
  application:
    name: testdemo-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: 5212010
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
spring:
  profiles: test
server:
  port: 8001
mybatis:
  type-aliases-package: com.zhirong.testdemo.pojo
#  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
spring:
  application:
    name: testdemo-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: 5212010
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/